// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnFVxjf6hZjuSErhrTDJ9r56H2SdItAnc',
    appId: '1:898478202267:web:42373e37f5dbf78534553e',
    messagingSenderId: '898478202267',
    projectId: 'andy-qr',
    authDomain: 'andy-qr.firebaseapp.com',
    storageBucket: 'andy-qr.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxzHPZmO7aGoB6WEmZVkTZdmjz5osydiY',
    appId: '1:898478202267:android:7323d898c524b4d534553e',
    messagingSenderId: '898478202267',
    projectId: 'andy-qr',
    storageBucket: 'andy-qr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD669T_cyMwiRUiYKLPbbZaWlC2kvtHE7g',
    appId: '1:898478202267:ios:c94eb19ae065487f34553e',
    messagingSenderId: '898478202267',
    projectId: 'andy-qr',
    storageBucket: 'andy-qr.appspot.com',
    androidClientId: '898478202267-b8p5l8f7k134qss2kkrtnmmikbkffrvl.apps.googleusercontent.com',
    iosClientId: '898478202267-cbl82812660de9qpdt2opgrk2vt8qpp3.apps.googleusercontent.com',
    iosBundleId: 'com.example.andyQr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD669T_cyMwiRUiYKLPbbZaWlC2kvtHE7g',
    appId: '1:898478202267:ios:c94eb19ae065487f34553e',
    messagingSenderId: '898478202267',
    projectId: 'andy-qr',
    storageBucket: 'andy-qr.appspot.com',
    androidClientId: '898478202267-b8p5l8f7k134qss2kkrtnmmikbkffrvl.apps.googleusercontent.com',
    iosClientId: '898478202267-cbl82812660de9qpdt2opgrk2vt8qpp3.apps.googleusercontent.com',
    iosBundleId: 'com.example.andyQr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnFVxjf6hZjuSErhrTDJ9r56H2SdItAnc',
    appId: '1:898478202267:web:280f189a8665f67034553e',
    messagingSenderId: '898478202267',
    projectId: 'andy-qr',
    authDomain: 'andy-qr.firebaseapp.com',
    storageBucket: 'andy-qr.appspot.com',
  );
}
